#!/bin/bash
BLUE="\033[1;34m"
ENDCOLOR="\e[0m"

echo
echo -ne $BLUE"[i] "$ENDCOLOR; echo "Checking for outdated Ruby Gems"
echo
gem outdated
echo

while true; do
    read -p "Do you want to update all Ruby Gems? " yn
    case $yn in
        [Yy]* ) gem update; break;;
        [Nn]* ) exit;;
        * ) echo; echo "Please answer yes or no. "; echo;;
    esac
done
