#!/usr/bin/env python3

import os
import apt
import subprocess
import sys
from updateactions import (print_message, elevate_privileges, take_ownership, update_packages,
                           install_package, remove_package, pip_package_install,gem_package_install,
                           install_golang_module, create_directory, remove_directory, sync_git_repo,
                           run_scripts)
from config import (personal_repo_directory, external_tools_directory, directories_to_remove,
                    packages_to_install, packages_to_remove, pip_packages, gem_packages,
                    golang_modules_to_install, ext_repositories_to_sync,
                    personal_repositories_to_sync)

def main():
    # Get sudo privileges
    if elevate_privileges(): sys.exit(1)

    # Sync the script with Github version
    print_message("blue", "Syncing 'update-kali' script")
    script_git_status = subprocess.Popen(["git", "-C", os.path.dirname(os.path.realpath(__file__)),
                                          "pull", "origin", "main"], stdout=subprocess.PIPE)
    script_git_status_output = script_git_status.communicate()[0]
    if "Already up to date" not in script_git_status_output.decode():
        print_message("error", "Script Updated. Please run the new version.\n")
        sys.exit(1)

    # Update and upgrade apt packages
    print_message("blue", "General Update")
    update_packages()

    # Install or remove specified apt packages
    print_message("blue", "Checking installed packages")
    apt_cache = apt.Cache()
    for package in packages_to_install:
        install_package(package, apt_cache)
    for package in packages_to_remove:
        remove_package(package, apt_cache)

    # Install python modules
    print_message("blue", "Checking python modules")
    installed_pip_packages = [r.decode().split('==')[0] for r in \
        subprocess.check_output([sys.executable, '-m', 'pip', 'freeze']).split()]
    pip_package_install(pip_packages, installed_pip_packages)

    # Install gem packages
    print_message("blue", "Checking ruby gems")
    gemlist = subprocess.Popen(["gem list | awk '{ print $1 }'"], shell=True, stdout=subprocess.PIPE).stdout
    installed_gem_packages = gemlist.read().decode("utf-8").split("\n")
    gem_package_install(gem_packages, installed_gem_packages)

    # Take ownership of the external tools directory
    take_ownership(external_tools_directory)

    # Install golang tools
    print_message("blue", "Checking golang modules")
    for module in golang_modules_to_install:
        install_golang_module(module)

    # Create and remove specified directories
    print_message("blue", "Checking directory structure")
    create_directory(personal_repo_directory)
    create_directory(external_tools_directory)
    for directory in directories_to_remove:
        remove_directory(directory)

    # Sync git repositories
    print_message("blue", "Syncing git repositories")
    for repo in personal_repositories_to_sync:
        #sync_git_repo(repo.replace(".git", ""), personal_repo_directory)
        sync_git_repo(repo, personal_repo_directory)
    for repo in ext_repositories_to_sync:
        sync_git_repo(repo, external_tools_directory)

    # Run *.sh and *.py files in the /scripts directory
    print_message("blue", "Running scripts")
    run_scripts()

    print("\nAll done. Go break stuff.\n")


if __name__ == '__main__':
    main()
