#!/bin/bash
GREEN="\033[1;32m"
ENDCOLOR="\e[0m"

echo
echo -ne $GREEN">>> "$ENDCOLOR; echo "Checking for outdated Python modules"
echo
pip3 list --outdated
echo

while true; do
    read -p "Do you want to update all python modules? " yn
    case $yn in
        [Yy]* ) pip3 list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip3 install -U; break;;
        [Nn]* ) exit;;
        * ) echo; echo "Please answer yes or no. "; echo;;
    esac
done
