#!/usr/bin/env python3

import os
import apt
import subprocess
import sys
from updateactions import *
from config import *

def main():
    # Set variables
    cache = apt.Cache()
    home_dir = os.getenv("HOME")
    personal_repo_directory = home_dir + personal_repo_dir
    external_repo_directory = home_dir + external_repo_dir

    # Update and upgrade apt packages
    update_packages()

    # Install additional packages
    print_bold_green("Checking installed packages")
    for package in packages_to_install:
        package_install(package, cache)

    # Install python modules
    installed_pip_packages = [r.decode().split('==')[0] for r in \
        subprocess.check_output([sys.executable, '-m', 'pip', 'freeze']).split()]
    pip_package_install(pip_packages, installed_pip_packages)

    # Create and remove specified directories
    print_bold_green("Creating directory structure")
    create_directory(personal_repo_directory)
    create_directory(external_repo_directory)
    for directory in directories_to_remove:
        remove_directory(directory)

    # Sync git repositories
    print_bold_green("Syncing git repositories")
    git_sync('git@github.com:rafaelh/dotfiles.git', home_dir + '/dotfiles')
    git_sync('git@github.com:rafaelh/security.git', personal_repo_directory + '/security')
    git_sync('git@github.com:rafaelh/notes.git', personal_repo_directory + '/notes')
    git_sync('https://github.com/danielmiessler/SecLists', external_repo_directory + '/seclists')
    git_sync('https://github.com/SecureAuthCorp/impacket', external_repo_directory + '/impacket')
    git_sync('https://github.com/swisskyrepo/PayloadsAllTheThings', external_repo_directory + '/payloadsallthethings')

    # Run *.sh and *.py files in the /scripts directory
    run_scripts()

    # Show status of optional systemd services
    print_bold_green("Status of optional services")
    systemd_services = ['sshd', 'postgresql']
    for system in systemd_services:
        if check_service_status(system) == False:
            print_green(system + " is active")
        else:
            print_red(system + " is inactive")

    print_grey("All done. Go break stuff.")


if __name__ == '__main__':
    main()


'''
TODO:
make sudo invocation nicer

sudo apt remove -y chromium

move git repos to config file

systemctl enable postresql
system start postgresql

start making it generically useful

'''
