#!/usr/bin/env python3

import os
import sys
from config import golang_modules_to_install

def update_golang_module(module):
    ''' Install the specified Golang module '''
    modulename = module.split("/")[-1].lower()
    if os.path.exists("/opt/" + modulename):
        print("Updating go module " + modulename)
        os.environ["GOPATH"] = "/opt/" + modulename
        cmdstring = "sudo -E go get -u " + module
        os.system(cmdstring)

if __name__ == '__main__':
    ''' Update the Go modules defined in config.py. '''

    print("\n\033[1;32;40m>>> \033[1;37;40m Updating Go modules\033[0;37;0m")
    for module in golang_modules_to_install:
        update_golang_module(module)